
#this file was generated by the config script

#vpath rules for sorce files
vpath %.html	src
vpath %.js	src
vpath %.css	src
vpath %.png	src

#vpath rules for build files
vpath %.link	build
vpath %.url	build

all: dist
.PHONY:dist
dist: build
	-mkdir dist/
	cp build/index.html.link dist/index.html
.PHONY:build
build: build/index.html.link
.PHONY:clean
clean:
	-rm -r build/ dist/
.PHONY:configure
configure:
	python config.py
build/%/:src/%/
	mkdir -p $@
#%.link:%
#	python Linker.py $< $@
build/%.url:build/%.link
	python Assambler.py $< $@
#dependecis for file src/index.html
build/index.html.link: index.html build/UI.css.url build/env.js.url build/UI.js.url build/script.js.url
	python Linker.py $< $@

#dependecis for file src/UI.css
build/UI.css.link: UI.css build/Images/on.png.url build/Images/play.png.url build/Images/pause.png.url build/Images/left.png.url build/Images/right.png.url build/Images/up.png.url build/Images/down.png.url
	python Linker.py $< $@

#dependecis for file src/Images/on.png
build/Images/on.png.link: Images/on.png  build/Images
	python Linker.py $< $@

#dependecis for file src/Images/play.png
build/Images/play.png.link: Images/play.png  build/Images
	python Linker.py $< $@

#dependecis for file src/Images/pause.png
build/Images/pause.png.link: Images/pause.png  build/Images
	python Linker.py $< $@

#dependecis for file src/Images/left.png
build/Images/left.png.link: Images/left.png  build/Images
	python Linker.py $< $@

#dependecis for file src/Images/right.png
build/Images/right.png.link: Images/right.png  build/Images
	python Linker.py $< $@

#dependecis for file src/Images/up.png
build/Images/up.png.link: Images/up.png  build/Images
	python Linker.py $< $@

#dependecis for file src/Images/down.png
build/Images/down.png.link: Images/down.png  build/Images
	python Linker.py $< $@

#dependecis for file src/env.js
build/env.js.link: env.js 
	python Linker.py $< $@

#dependecis for file src/UI.js
build/UI.js.link: UI.js 
	python Linker.py $< $@

#dependecis for file src/script.js
build/script.js.link: script.js build/Images/open.png.url build/Images/closed.png.url
	python Linker.py $< $@

#dependecis for file src/Images/open.png
build/Images/open.png.link: Images/open.png  build/Images
	python Linker.py $< $@

#dependecis for file src/Images/closed.png
build/Images/closed.png.link: Images/closed.png  build/Images
	python Linker.py $< $@

