
#this file was generated by the config script

#vpath rules for sorce files
vpath %.html	src
vpath %.js	src
vpath %.css	src
vpath %.png	src

#vpath rules for build files
vpath %.link	build
vpath %.url	build

all: dist
dist: build
	cp build/index.html.link dist/index.html
build: index.html.link
.PHONY:clean
clean:
	-rm -r build/* dist/*
%.link:%
	python Linker.py $< $@
%.url:%.link
	python Assambler.py $< $@
#dependecis for file src/index.html
index.html.link: index.html UI.css.url env.js.url UI.js.url script.js.url
	python Linker.py $< $@

#dependecis for file src/UI.css
UI.css.link: UI.css Images/on.png.url Images/play.png.url Images/pause.png.url Images/left.png.url Images/right.png.url Images/up.png.url Images/down.png.url
	python Linker.py $< $@

#dependecis for file src/Images/on.png
Images/on.png.link: Images/on.png 
	python Linker.py $< $@

#dependecis for file src/Images/play.png
Images/play.png.link: Images/play.png 
	python Linker.py $< $@

#dependecis for file src/Images/pause.png
Images/pause.png.link: Images/pause.png 
	python Linker.py $< $@

#dependecis for file src/Images/left.png
Images/left.png.link: Images/left.png 
	python Linker.py $< $@

#dependecis for file src/Images/right.png
Images/right.png.link: Images/right.png 
	python Linker.py $< $@

#dependecis for file src/Images/up.png
Images/up.png.link: Images/up.png 
	python Linker.py $< $@

#dependecis for file src/Images/down.png
Images/down.png.link: Images/down.png 
	python Linker.py $< $@

#dependecis for file src/env.js
env.js.link: env.js 
	python Linker.py $< $@

#dependecis for file src/UI.js
UI.js.link: UI.js 
	python Linker.py $< $@

#dependecis for file src/script.js
script.js.link: script.js Images/closed.png.url
	python Linker.py $< $@

#dependecis for file src/Images/closed.png
Images/closed.png.link: Images/closed.png 
	python Linker.py $< $@

